export const SUCCESS = "SUCCESS";

export const FAILURE = "FAILURE";

export const USER_INPUT = "USER_INPUT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const ADD_PROFILE = "ADD_PROFILE";
export const REMOVE_PROFILE = "REMOVE_PROFILE";

export const SET_DB_PROFILE = "SET_DB_PROFILE";
export const REMOVE_DB_PROFILE = "REMOVE_DB_PROFILE";

export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAIL = "EDIT_POST_FAIL";

export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const FETCH_POSTS_COMMENTS = "FETCH_POSTS_COMMENTS";
export const REMOVE_POSTS_COMMENTS = "REMOVE_POSTS_COMMENTS";

export const FETCH_USER_POSTS = "FETCH_USER_POSTS";
export const REMOVE_USER_POSTS = "REMOVE_USER_POSTS";

export const SET_OTHER_USER_PROFILE = "SET_OTHER_USER_PROFILE";
export const REMOVE_OTHER_USER_PROFILE = "REMOVE_OTHER_USER_PROFILE";

export const SET_OTHER_USER_POSTS = "SET_OTHER_USER_POSTS";
export const REMOVE_OTHER_USER_POSTS = "REMOVE_OTHER_USER_POSTS";

export const SET_USER_MESSAGES = "SET_USER_MESSAGES";
export const REMOVE_USER_MESSAGES = "REMOVE_USER_MESSAGES";

export const AUTH_LOGOUT = 'AUTH_LOGOUT';